import type { NavigationItem } from "@/types/navigation.types";

export const NAVIGATION_ITEMS: NavigationItem[] = [
  {
    id: 1,
    key: "dashboard",
    title: {
      en: "Dashboard",
      ar: "لوحة القيادة",
    },
    icon: "LayoutDashboard",
    route: "/",
    sort_order: 1,
    is_active: true,
    is_default: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    key: "pos",
    title: {
      en: "Point of Sale",
      ar: "نقطة البيع",
    },
    icon: "ShoppingCart",
    route: "/pos",
    sort_order: 2,
    is_active: true,
    is_default: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    key: "orders",
    title: {
      en: "Orders",
      ar: "الطلبات",
    },
    icon: "Package",
    route: "/orders",
    sort_order: 3,
    is_active: true,
    is_default: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    children: [
      {
        id: 31,
        key: "all-orders",
        title: {
          en: "All Orders",
          ar: "جميع الطلبات",
        },
        icon: "List",
        route: "/orders",
        sort_order: 1,
        is_active: true,
        is_default: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 32,
        key: "orders-timeline",
        title: {
          en: "Orders Timeline",
          ar: "الجدول الزمني للطلبات",
        },
        icon: "TrendingUp",
        route: "/orders/timeline",
        sort_order: 2,
        is_active: true,
        is_default: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 33,
        key: "order-status-screen",
        title: {
          en: "Status Screen",
          ar: "شاشة الحالة",
        },
        icon: "MonitorPlay",
        route: "/orders/status",
        sort_order: 3,
        is_active: true,
        is_default: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 4,
    key: "customers",
    title: {
      en: "Customers",
      ar: "العملاء",
    },
    icon: "Users",
    route: "/customers",
    sort_order: 4,
    is_active: true,
    is_default: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    key: "services",
    title: {
      en: "Services",
      ar: "الخدمات",
    },
    icon: "Shirt",
    route: "/service-offerings",
    sort_order: 5,
    is_active: true,
    is_default: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    children: [
      {
        id: 51,
        key: "service-offerings",
        title: {
          en: "Offerings",
          ar: "العروض",
        },
        icon: "List",
        route: "/service-offerings",
        sort_order: 1,
        is_active: true,
        is_default: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 52,
        key: "product-categories",
        title: {
          en: "Categories",
          ar: "الفئات",
        },
        icon: "Grid3x3",
        route: "/admin/product-categories",
        sort_order: 2,
        is_active: true,
        is_default: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 53,
        key: "service-list",
        title: {
          en: "Service List",
          ar: "خدمات",
        },
        icon: "Tags",
        route: "/admin/product-types",
        sort_order: 3,
        is_active: true,
        is_default: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 54,
        key: "service-actions",
        title: {
          en: "Service Actions",
          ar: "إجراءات الخدمة",
        },
        icon: "Wand2",
        route: "/admin/service-actions",
        sort_order: 4,
        is_active: true,
        is_default: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 6,
    key: "expenses",
    title: {
      en: "Expenses",
      ar: "المصاريف",
    },
    icon: "DollarSign",
    route: "/expenses",
    sort_order: 6,
    is_active: true,
    is_default: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 7,
    key: "reports",
    title: {
      en: "Reports",
      ar: "التقارير",
    },
    icon: "BarChart3",
    route: "/reports",
    sort_order: 7,
    is_active: true,
    is_default: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 8,
    key: "settings",
    title: {
      en: "Settings",
      ar: "الإعدادات",
    },
    icon: "Settings",
    route: "/settings",
    sort_order: 8,
    is_active: true,
    is_default: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    children: [
      {
        id: 81,
        key: "users",
        title: {
          en: "Users",
          ar: "المستخدمين",
        },
        icon: "Shield",
        route: "/admin/users",
        sort_order: 1,
        is_active: true,
        is_default: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },

      {
        id: 83,
        key: "settings",
        title: {
          en: "Settings",
          ar: "الإعدادات",
        },
        icon: "Settings",
        route: "/settings",
        sort_order: 3,
        is_active: true,
        is_default: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  },
];
